"""empty message

Revision ID: 4bac9eae3a46
Revises: 7cd9da8abae8
Create Date: 2022-10-28 11:26:29.691264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bac9eae3a46'
down_revision = '7cd9da8abae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residence', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('answers', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_form')
    # ### end Alembic commands ###
