"""empty message

Revision ID: 6152e0f9ca9c
Revises: a14829a07cc0
Create Date: 2022-11-08 09:20:30.057377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6152e0f9ca9c'
down_revision = 'a14829a07cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('formName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'formName')
    # ### end Alembic commands ###
