"""empty message

Revision ID: c769eba86e68
Revises: d44693dd0aef
Create Date: 2022-11-07 11:25:37.475337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c769eba86e68'
down_revision = 'd44693dd0aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_form', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_form', 'description')
    # ### end Alembic commands ###
