"""empty message

Revision ID: d44693dd0aef
Revises: 4bac9eae3a46
Create Date: 2022-11-06 10:55:35.535075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44693dd0aef'
down_revision = '4bac9eae3a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('questions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('startDate', sa.String(), nullable=True),
    sa.Column('endDate', sa.String(), nullable=True),
    sa.Column('ownerId', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('consumer', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_question')
    op.drop_table('survey_form')
    op.drop_table('section')
    # ### end Alembic commands ###
